version: '3'
services:

  node:
    volumes:
      - ../frontend:/app:cached

  mariadb:
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql:cached

  php:
    environment:
      TEST_USERS_PASSWORD: ${TEST_USERS_PASSWORD}
      ENVIRONMENT: ${ENVIRONMENT}
    volumes:
      - ../drupal:/var/www/html:cached
      - ../${BACKUP_DIR}:/var/www/html/${BACKUP_DIR}:cached

  nginx:
    volumes:
      - ../drupal:/var/www/html:cached
